source 'https://github.com/CocoaPods/Specs.git'

target 'ZzishSDK', :exclusive => true do
  pod "ZzishSDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ZzishSDK", :path => "../"

  
end
